import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Box from "@mui/material/Box";
import Container from "@mui/material/Container";
import Grid from "@mui/material/Grid";

interface PlayerProp {
  civ: number;
  name: string;
  profile_id: number;
  rating: number;
  rating_change: number;
  won: null;
}

const civilization = [
  {
    id: 0,
    name: "Abbasid",
  },
  {
    id: 1,
    name: "Chinese",
  },
  {
    id: 2,
    name: "Delhi",
  },
  {
    id: 3,
    name: "English",
  },
  {
    id: 4,
    name: "French",
  },
  {
    id: 5,
    name: "Holy Romand Empire",
  },
  {
    id: 6,
    name: "Mongols",
  },
  {
    id: 7,
    name: "Rus",
  },
];

console.log(civilization);

const Player: NextPage = (request) => {
  return (
    <div>
      <Head>
        <title>AoE IV - Player</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container maxWidth="xl">
          <Box sx={{ flexGrow: 1 }}>
            <Grid container spacing={2}>
              <Grid item xs={8}>
                <h3>Latest match</h3>
                {request.request.map(
                  ({ started, match_id, players }: PlayerProp) => (
                    <div key={match_id}>
                      {players.map(
                        ({
                          name,
                          profile_id,
                          won,
                          civ,
                          rating,
                          team,
                        }: PlayerProp) => (
                          <div
                            className={won === true ? "won" : ""}
                            key={profile_id}
                          >
                            <Image
                              src={`/images/civs/${civ}.png`}
                              alt="Landscape picture"
                              width={25}
                              height={15}
                            />
                            {rating}-{name}
                          </div>
                        )
                      )}
                    </div>
                  )
                )}
              </Grid>
            </Grid>
          </Box>
        </Container>
      </main>
    </div>
  );
};

export const getServerSideProps = async () => {
  const res = await fetch(
    "https://aoeiv.net/api/player/matches?game=aoe4&profile_id=6943917&count=10"
  );
  // console.log(res.json());
  const request = await res.json();
  return {
    props: { request },
  };
};

export default Player;
