import type { NextPage } from "next";
import React from "react";
import Head from "next/head";
import Image from "next/image";
import { PlayerStats } from "../../components/PlayersStats";

interface MatchProps {
  started: number;
  match_id: string;
  players: [];
}

interface PlayerProp {
  civ: number;
  name: string;
  profile_id: number;
  rating: number;
  rating_change: number;
  won: null;
  team: number;
}

const Player: NextPage = ({ matches }) => {
  console.log(matches);
  return (
    <div>
      <Head>
        <title>AoE IV - Player</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {matches.map(({ started, match_id, players }: MatchProps) => (
          <React.Fragment key={players[0].profile_id}>
            <div className="text-3xl font-bold underline">
              {players[0].name}
            </div>
          </React.Fragment>
        ))}
      </main>
    </div>
  );
};

export async function getServerSideProps() {
  const [matchesRes] = await Promise.all([
    fetch(`https://aoe4world.com/api/v0/players/4635035`),
  ]);
  const [matches] = await Promise.all([matchesRes.json()]);
  return { props: { matches } };
}

export default Player;
