import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import PlayerCard from "../components/PlayerCard";
import Link from "next/link";

const Home: NextPage = (request) => {
  return (
    <div>
      <Head>
        <title>AoE Rankings</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="sticky bg-[#1d1d1d]">
        <ul className="flex justify-start align-center align-center w-full ">
          <li>
            <Link href="/">
              <a className="block py-4 px-4 text-md hover:bg-[#BB86FC] hover:text-black">
                Home
              </a>
            </Link>
          </li>
          <li>
            <Link href="/">
              <a className="block py-4 px-4 text-md hover:bg-[#BB86FC] hover:text-black">
                Leaderboard
              </a>
            </Link>
          </li>
          <li>
            <Link href="/">
              <a className="block py-4 px-4 text-md hover:bg-[#BB86FC] hover:text-black">
                Statistics
              </a>
            </Link>
          </li>
        </ul>
      </nav>

      <main className={`container mx-auto my-10`}>
        <PlayerCard request={request.request} />
        <h4>Check out our features</h4>
        <div className="columns-3 mt-10">
          <div className="w-full text-center">
            <h3 className="mb-4 text-lg">Ranked and Quickmatch leaderboard</h3>
            <div className="border-2 py-6 text-center border-[#BB86FC] rounded-md">
              <Image
                src="/images/civs/leaderboard-preview.png"
                alt="Picture of the author"
                width={350}
                height={250}
              />
            </div>
          </div>
          <div className="w-full text-center">
            <h3 className="mb-4 text-lg">Player statistics</h3>
            <div className="border-2 py-6 text-center border-[#BB86FC] rounded-md">
              <Image
                src="/images/civs/2022img_index_02_en@2x.png"
                alt="Picture of the author"
                width={350}
                height={250}
              />
            </div>
          </div>
          <div className="w-full text-center">
            <h3 className="mb-4 text-lg">Match histroy</h3>
            <div className="border-2 py-6 text-center border-[#BB86FC] rounded-md">
              <Image
                src="/images/civs/2022img_index_02_en@2x.png"
                alt="Picture of the author"
                width={350}
                height={250}
              />
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export const getStaticProps = async () => {
  const res = await fetch("https://aoe4world.com/api/v0/leaderboards/rm_solo");
  // console.log(res.json());
  const request = await res.json();
  return {
    props: { request },
  };
};

export default Home;
