import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import TopPlayers from "../components/TopPlayers";

const Home: NextPage = (request) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>AoE Rankings</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <TopPlayers request={request.request} />
      </main>
    </div>
  );
};

export const getStaticProps = async () => {
  const res = await fetch(
    "https://aoeiv.net/api/leaderboard?game=aoe4&event_leaderboard_id=1&start=1&count=10"
  );
  // console.log(res.json());
  const request = await res.json();
  return {
    props: { request },
  };
};

export default Home;
